// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkA8BUDgDqEIVqwyd8GbXTPIJPJ_EHbVk',
    appId: '1:660131140128:web:fb4965ef2c687931876245',
    messagingSenderId: '660131140128',
    projectId: 'stockmanagement-a9ca1',
    authDomain: 'stockmanagement-a9ca1.firebaseapp.com',
    storageBucket: 'stockmanagement-a9ca1.firebasestorage.app',
    measurementId: 'G-GVKJC2JX28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOG0kmhoHbOh6koogyW4com27f6brxY18',
    appId: '1:660131140128:android:ba8152534ac49a5c876245',
    messagingSenderId: '660131140128',
    projectId: 'stockmanagement-a9ca1',
    storageBucket: 'stockmanagement-a9ca1.firebasestorage.app',
  );
}
